apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gcservice-operator
  namespace: free5gc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: free5gcservice-operator
  template:
    metadata:
      labels:
        name: free5gcservice-operator
    spec:
      serviceAccountName: free5gcservice-operator
      containers:
        - name: free5gcservice-operator
          # Replace this with the built image name
          image: sufuf3/free5gc-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "free5gcservice-operator"
